# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false

include:
 - r: oldrel
 - r: release
 - r: devel

addons:
  apt:
    packages:
      - unixodbc-dev
      - libudunits2-dev

r_packages:
 - EnvStats

r_github_packages:
 - tidyverse/tidyverse
 - eclarke/ggbeeswarm
 - awalker89/openxlsx
 - yihui/animation
 - rstats-db/odbc
 - edzer/units
 - jimhester/covr
 
after_success:
 - Rscript -e 'covr::codecov()'